### ISSUE TITLE
Enhancement Request - A5E (Advanced 5th Edition)

### ISSUE THREAD

**Issue by villain4hire78** [AngryBeaver/beavers-system-interface#18]
Are there plans to add A5E to the Beaver System Interface?
![level_up_logo_hires](https://github.com/AngryBeaver/beavers-system-interface/assets/14360370/40327d5c-7d7e-4286-b84b-400d92176ac3)

**Comment by AngryBeaver** [comment]
I will look into it. When it's simple compatible i will do it soon.

**Comment by AngryBeaver** [comment]
seems simple i already got 80% done but has to wait now for tomorrow.

**Comment by villain4hire78** [comment]
Thank you! That was really quick. I look forward to using it soon. :)

**Comment by AngryBeaver** [comment]
so starting with the 20% left (attaching it to the sheets) i encountered an obstacle that i can/should not overcome so no currently not possible. 

Problem:
A5E is using svelte and this is not simple extendable. I do not know svelte but i believe its like react/angular e.g. javascript is core and creates the app. This would need me to extend the app not the html. Usually in foundry we have an old jquery style like build e.g. html that gets enriched with javascript functionality. 

![image](https://github.com/AngryBeaver/beavers-system-interface/assets/10677192/1d3c33fa-e87e-4533-82e0-0726357114ab)

While with some time it might be possible to extend it the dirty way and bypass svelte and combine it with jquery i do not think this is a good idea and ofc developer of a5e will kill me if they see how i bypass their svelte.
I got very close but it is not useable that way i would need to dive into their application code and find or create extensionpoints (which they then must approve). Which is not the easy path i currently am willing to do.
 

jfi:
I also personally believe in app based javascripts rather then jquerry for developing, but the downside is it is not meant to be extended from the outside.


I leave this open maybe i find the passion someday to do more here as i latly see more of svelte comeing into VTT-Foundry or foundry will come up with unified svelte support maybe with standardised extensionpoints.

**Comment by villain4hire78** [comment]
Thank you for looking into it! That was a very extensive, and highly appreciated. (I may see if I can learn svelte)

**Comment by AngryBeaver** [comment]
Well looked into there actor-sheet and no there is currently no extension point visible to add tabs to it.

So challenge accepted i created a dirty path and extend svelte with jquery... this is evil but works for now.
Also those guys at a5e seems not to hold on to standards (item-sheets are no FormApplication anymore i had to fake a lot) (actor-sheets do not even update when the actor is updated from outside of the sheet. I had to hook a rerendering myself to it)

There are still some minor bugs (like you can not delete last recipe on actor or you can not enter textinformation for recipes) but all main paths are functional

needs now also a new version of beavers-crafting 3.4.3
