### ISSUE TITLE
Cannot move in Foundry V11

### ISSUE THREAD

**Issue by qjuppet** [AngryBeaver/beavers-system-interface#19]
I cannot move my actors in Foundry V11, I checked the logs and got this error:
![image](https://github.com/AngryBeaver/beavers-system-interface/assets/13199998/f7613bfa-18cd-4f75-a292-e475d385f944)
I looked a bit in the code and was able to make it work: by replacing this line:
`const token = canvas.tokens?.objects?.children.find(token => this.actorId.endsWith(token?.actor?.uuid));`
by:
`const token = canvas.tokens?.objects?.children.find(token => this.actorId.endsWith(token?.document?.actorId));`

First time looking into modules of Foundry so there's probably more to check, maybe other places with similar issues.

Thanks a lot for this module it will be very helpful for my future tabletop games.

**Comment by AngryBeaver** [comment]
i need to play with this a bit more but first test shows me both should work token.actor.uuid will give a uuid of an actor and token.document.actorId will give an id for the actor. I currently can't see that token.actor.uuid is broken but i just now only tested on v12.232.  I will keep looking in other vtt versions and will consider your improvement thx for your feedback.

**Comment by AngryBeaver** [comment]
tested with v11.315 it does work as expected. 
However it might have been possible that :
1.) on the scene you had been the token you tried to control was missing.
2.) you had deleted the orginal actor the token was referencing to. 

The documentation for v11 also stated that actor should be available on tokens.
but i guess when the original actor is missing the linking is broken i will test your variant on all supported vtt versions.

**Comment by AngryBeaver** [comment]
2) is impossible to keep on when you refresh your browser your user ends up with no actor -> so you can't controll anything that seems normal. 

And 1) will always be a problem, you can't controll a token that is not on the scene :-)
Also your solution seems only to work for  TokenDocument5e:
![image](https://github.com/AngryBeaver/beavers-system-interface/assets/10677192/f7bd3b57-650f-4617-923a-a07a688cd2e3)
While the TokenDocument that is base within all systems:
![image](https://github.com/AngryBeaver/beavers-system-interface/assets/10677192/adfc2922-89fe-429b-8814-9c278fb3a99f)
Also when you look at the api:
https://foundryvtt.com/api/classes/client.TokenDocument.html#actor
there is no actorId there.

I will stick up with my solution. When the actor your controller is controlling does not have a token on the scene or the actor you controll is deleted then yes it might end up with no tokens be moved in all other cases it still seems to work. At least i could not reproduce this in any other disturbing way.
