### ISSUE TITLE
Can't migrate recipes

### ISSUE THREAD

**Issue by ctbritt** [AngryBeaver/beavers-system-interface#21]
Getting several of these errors: 
![CleanShot 2024-08-30 at 10 26 56@2x](https://github.com/user-attachments/assets/de43fdef-0f77-4acc-8394-c378108b60b9)

**Comment by AngryBeaver** [comment]
i will have a look i asume bsa-dnd5e is up to date ?

**Comment by ctbritt** [comment]
Sure is. v3.3.1

**Comment by AngryBeaver** [comment]
no the module bsa-dnd5e should be currently at version:
https://github.com/AngryBeaver/bsa-dnd5e/releases/tag/v2.1.0

if you just upgraded the beavers-crafting it has major changes and need a compatible bsa-x implementation

**Comment by AngryBeaver** [comment]
does look promising on my side ?
e.g could not verify that this happens here with bsa-dnd5e v2.1.0
but i found a ui bug in the representation of tool tests.

anyway if you keep having trouble maybe there is another error in your logs and this is only a follow up ?
Can you open the new tool config option in bsa-dnd5e Settings ?

**Comment by AngryBeaver** [comment]
v2.1.2 fixed the visual bug i found but i can not reproduce your bug.
![image](https://github.com/user-attachments/assets/172fe6ca-3ad3-4ab0-9a09-52329fc87dfd)

**Comment by AngryBeaver** [comment]
I assume this can be closed ?
